logging:
  level:
    root: INFO
    org.apache.http.wire: DEBUG
    org.elasticsearch: DEBUG
    org.elasticsearch.client: TRACE
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: trace
